import wikipedia
import os
from datetime import datetime



def calculate_elapsed_time(begin_time_, end_time_):
    elapsed_time_ = end_time_ - begin_time_
    days = elapsed_time_.days
    seconds = elapsed_time_.seconds
    milliseconds = elapsed_time_.microseconds // 1000
    hours, remainder = divmod(seconds, 3600)
    minutes, seconds = divmod(remainder, 60)
    years, days = divmod(days, 365)
    months, days = divmod(days, 30)
    formatted_elapsed_time_ = f"{years:04}:{months:02}:{days:02}:{hours:02}:{minutes:02}:{seconds:02}:{milliseconds:03}"
    return formatted_elapsed_time_


def collect_and_save_articles_wikipedia(subjects_to_find_, destination_folder_="dati_wikipedia"):
    """
    Search and download Wikipedia articles by topic,
    saving them in separate text files.

    Args:
        subjects_to_find_ (list): List of strings containing the names of the arguments to search for.
        destination_folder_ (str): The name of the folder where to save the files.
    """
    print("collect_and_save_articles_wikipedia() - BEGIN")
    # 1. Configurazione Iniziale
    print(f"Tentativo di creare la cartella: {destination_folder_}")
    os.makedirs(destination_folder_, exist_ok=True)
    wikipedia.set_lang("en")  # Imposta la lingua di Wikipedia (italiano)

    downloaded_articles_ = 0

    for subject_ in subjects_to_find_:
        print(f"\n--- Elaborazione di: '{subject_}' ---")

        try:
            # 2. Ottenere la Pagina (Potrebbe sollevare un'eccezione se non trovata)
            page_ = wikipedia.page(subject_, auto_suggest=False)

            # 3. Pulizia del Nome del File
            # Rimuove caratteri non validi per i nomi di file
            file_name_ = "".join(c for c in subject_ if c.isalnum() or c in (' ', '_')).rstrip().replace(' ', '_')
            file_path_ = os.path.join(destination_folder_, f"{file_name_}.txt")

            # 4. Salvare il Contenuto nel File
            with open(file_path_, 'w', encoding='utf-8') as f:
                # La proprietà 'content' restituisce l'intero testo della page_
                f.write(page_.content)

            print(f"✔ Articolo salvato in: {file_path_}")
            downloaded_articles_ += 1

        except wikipedia.exceptions.PageError:
            print(f"❌ Errore: Pagina di Wikipedia non trovata per l'subject_ '{subject_}'. Saltato.")
        except wikipedia.exceptions.DisambiguationError as e:
            print(f"⚠️ Attenzione: L'subject_ '{subject_}' è ambiguo. Opzioni: {e.options[:5]}. Saltato.")
        except Exception as e:
            print(f"collect_and_save_articles_wikipedia() - Generic error while processing '{subject_}': {e}. Saltato.")

    print(f"\n--- Finito. {downloaded_articles_} articoli salvati. ---")
    print("collect_and_save_articles_wikipedia() - END")



if __name__ == "__main__":
    print("__main__() - BEGIN")

    begin_time = datetime.now()

    subjects_to_find_1 = [
        "Liver",
        "Liver cirrhosis",
        "Bile",
        "Liver disease",
        "Human anatomy",
        "Hepatotoxicity",
        "Liver failure",
        "Liver support system",
        "Elevated transaminases",
        "Metabolic dysfunction–associated steatotic liver disease",
        "Liver regeneration",
        "Fatty liver disease",
        "Acute liver failure",
        "Hepatomegaly",
        "Lobules of liver",
        "Chronic liver disease",
        "Alanine transaminase",
        "AST/ALT ratio",
        "Liver transplantation",
        "Hepatorenal syndrome",
        "Hepatocellular carcinoma",
        "Liver metastasis",
        "Jaundice",
        "Bilirubin",
        "Pre-eclampsia",
        "Alkaline phosphatase",
        "Kupffer cell",
        "Paracetamol",
        "Shark liver oil",
        "HepaRG",
        "Liver cancer",
        "Alpha-1 antitrypsin deficiency",
        "Schistosomiasis",
        "Gallbladder",
        "Paracetamol poisoning",
        "Aspartate transaminase",
        "Lorazepam",
        "Cholangiocarcinoma",
        "Organ (biology)",
        "Urea-to-creatinine ratio",
        "Sarcoidosis",
        "Foie gras",
        "Alcoholic hepatitis",
        "Interventional radiology",
        "Polycystic liver disease",
        "Sulfamethoxazole",
        "Hypoalbuminemia",
        "Human serum albumin",
        "Blood test",
        "Anorexia nervosa",
        "Hepatitis",
        "Adult-onset Still's disease",
        "Intrahepatic cholestasis of pregnancy",
        "Alcoholic liver disease",
        "TNT",
        "Reye syndrome",
        "Primary sclerosing cholangitis",
        "Cholestasis",
        "Autoimmune hepatitis",
        "Liver cytology",
        "Bone tumor",
        "Basic metabolic panel",
        "Lipotropic",
        "Hepatic encephalopathy",
        "Liver biopsy",
        "Elevated alkaline phosphatase",
        "Hyperbilirubinemia in adults",
        "Hepatitis C",
        "Primary biliary cholangitis",
        "Sanford Rosenthal",
        "Wilson's disease",
        "Bromsulfthalein",
        "Ezetimibe",
        "Congestive hepatopathy",
        "Agaricus subrufescens",
        "Organ-on-a-chip",
        "Valproate",
        "Rodenticide",
        "Small intestine"
    ]


    subjects_to_find_2 = ["Blood",
                          "Hemoglobin",
                          "Glucose",
                          "Amino acid",
                          "Hormone",
                          "Blood plasma",
                          "Red blood cell",
                          "Ion",
                          "White blood cell",
                          "Cell (biology)",
                          "Protein",
                          "Gnathostomata",
                          "Platelet",
                          "Adaptive immune system",
                          "Coagulation",
                          "Blood vessel",
                          "Heart",
                          "Body fluid",
                          "Water",
                          "Human",
                          "Vertebrate",
                          "Lung",
                          "Circulatory system",
                          "Metabolic waste",
                          "Nutrient",
                          "Artery",
                          "Vein",
                          "Metabolism",
                          "Anatomy",
                          "Histology",
                          "Connective tissue",
                          "Fibrinogen",
                          "Oxygen",
                          "Fatty acid",
                          "Plasma protein",
                          "Blood lipids",
                          "Carbon dioxide",
                          "Urea",
                          "Lactic acid",
                          "Antibody",
                          "Tissue (biology)",
                          "Thermoregulation",
                          "Blood volume",
                          "Non-Newtonian fluid",
                          "Hemorheology",
                          "Cell nucleus",
                          "Endothelium",
                          "Organelle",
                          "Glycoprotein",
                          "Hematocrit",
                          "Immune system",
                          "Human blood group systems",
                          "Pathogen",
                          "Leukemia",
                          "Platelet plug",
                          "List of human blood components",
                          "Serum albumin",
                          "Lipoprotein",
                          "Electrolyte",
                          "Sodium in biology",
                          "Chloride",
                          "pH",
                          "Acid–base homeostasis",
                          "Base (chemistry)",
                          "Acid",
                          "pCO2",
                          "Bicarbonate",
                          "Homeostasis",
                          "Respiratory system",
                          "Urinary system",
                          "Arterial blood gas test",
                          "Reference ranges for blood tests",
                          "Protein structure",
                          "Pulmonary artery",
                          "Ventricle (heart)",
                          "Pulmonary vein",
                          "Venous blood",
                          "Skeletal muscle",
                          "Bone marrow",
                          "Haematopoiesis",
                          "Myelopoiesis",
                          "Thymus",
                          "Mediastinum",
                          "T cell",
                          "Endocrine gland",
                          "Hypothalamus",
                          "Kidney",
                          "Spleen",
                          "Urine",
                          "Mammal",
                          "Umbilical artery",
                          "Arteriole",
                          "Capillary",
                          "Venule",
                          "Oxygen saturation (medicine)",
                          "Fetus",
                          "Placenta",
                          "Fetal hemoglobin",
                          "Carbonic anhydrase",
                          "Carbamino",
                          "Allosteric regulation",
                          "Haldane effect",
                          "Bohr effect",
                          "Lymphatic system",
                          "Lymph",
                          "Thoracic duct",
                          "Subclavian vein",
                          "Erection",
                          "Erectile tissue",
                          "Penis",
                          "Clitoris",
                          "Blood donation",
                          "Carbon monoxide poisoning",
                          "Carbon monoxide",
                          "Carboxyhemoglobin",
                          "Cyanide",
                          "Methemoglobin",
                          "Sulfhemoglobinemia",
                          "Visual cortex",
                          "Biliverdin",
                          "Shock (circulatory)",
                          "Internal bleeding",
                          "Dehydration",
                          "Orthostatic hypotension",
                          "Syncope (medicine)",
                          "Cardiac output",
                          "Atherosclerosis",
                          "Perfusion",
                          "Hyperlipidemia",
                          "Hypertension",
                          "Diabetes",
                          "Thrombosis",
                          "Necrosis",
                          "Hematology",
                          "Anemia",
                          "Thalassemia",
                          "Malnutrition",
                          "Blood transfusion",
                          "Genetic disorder",
                          "Blood bank",
                          "Blood type",
                          "Sickle cell disease",
                          "Cancer",
                          "Polycythemia vera",
                          "Essential thrombocythemia",
                          "Precancerous condition",
                          "Myelodysplastic syndrome",
                          "Haemophilia",
                          "Hemarthrosis",
                          "Coagulopathy",
                          "Thrombophilia",
                          "Hepatitis B",
                          "Blood-borne disease",
                          "Biological hazard",
                          "Bloodstream infection",
                          "Sepsis",
                          "Malaria",
                          "Trypanosomiasis",
                          "ABO blood group system",
                          "Rh blood group system",
                          "Cross-matching",
                          "Intravenous therapy",
                          "Antibiotic",
                          "Chemotherapy",
                          "Bloodletting",
                          "Evidence-based medicine",
                          "Iron overload",
                          "Blood type",
                          "Polycythemia",
                          "Hippocrates",
                          "Erythrocyte sedimentation rate",
                          "Heredity",
                          "Autotransfusion",
                          "Blood pressure",
                          "Blood phobia",
                          "Blood substitute",
                          "Hemodynamics",
                          "Luminol",
                          "Oct-1-en-3-one",
                          "Blood residue",
                          "Pressure",
                          "Brachial artery",
                          "Cardiac cycle",
                          "Millimetre of mercury",
                          "Respiratory rate",
                          "Heart rate",
                          "Auscultation",
                          "Stethoscope",
                          "Mercury (element)",
                          "Sphygmomanometer",
                          "Ambulatory blood pressure",
                          "Arterial stiffness",
                          "Nervous system",
                          "Endocrine system",
                          "Baroreceptor",
                          "Hypotension",
                          "Stroke",
                          "Cardiovascular disease",
                          "Kidney failure",
                          "Stress (biology)",
                          "Sex",
                          "Peripheral artery disease",
                          "Aortic dissection",
                          "Pregnancy",
                          "Systolic hypertension",
                          "Intensive care medicine",
                          "Pulmonary circulation",
                          "Catheter",
                          "Jugular venous pressure",
                          "Respiratory disease",
                          "Central venous pressure",
                          "Portal venous pressure",
                          "Pulmonary edema",
                          "Pulmonary hypertension",
                          "Aortic pressure",
                          "Hypertension",
                          "Hypertensive emergency",
                          "Atrium (heart)"]

    subjects_to_find_3 = ["Skeleton",
                          "Human skeleton",
                          "Gray's Anatomy",
                          "Organ system",
                          "Human head",
                          "Hair",
                          "Neck",
                          "Torso",
                          "Thorax",
                          "Abdomen",
                          "Sex organ",
                          "Arm",
                          "Hand",
                          "Human leg",
                          "Foot",
                          "Human tooth",
                          "Bone",
                          "Muscle",
                          "Tendon",
                          "Ligament",
                          "Lymphatic vessel",
                          "Physiology",
                          "Embryology",
                          "Anatomical variation",
                          "Sugar",
                          "Iron",
                          "Health professional",
                          "Composition of the human body",
                          "Hydrogen",
                          "Carbon",
                          "Calcium",
                          "Phosphorus",
                          "Extracellular fluid",
                          "Body water",
                          "pH",
                          "Sodium",
                          "Potassium",
                          "Phosphate",
                          "List of human cell types",
                          "Extracellular matrix",
                          "Collagen",
                          "DNA damage (naturally occurring)",
                          "Human genome",
                          "DNA repair",
                          "DNA",
                          "Mutation",
                          "Genome",
                          "Genetics",
                          "Transcription (biology)",
                          "RNA",
                          "Microscope",
                          "Epithelium",
                          "Nervous tissue",
                          "Stomach",
                          "Human skin",
                          "Body cavity",
                          "Abdominopelvic cavity",
                          "Pleural cavity",
                          "Thoracic cavity",
                          "Pericardium",
                          "Infection",
                          "Pericardial fluid",
                          "Systole",
                          "Cardiac conduction system",
                          "Atrioventricular node",
                          "Sinoatrial node",
                          "Coronary arteries",
                          "Coronary artery disease",
                          "List of causes of death by rate",
                          "Ischemia",
                          "Cardiac muscle",
                          "Myocardial infarction",
                          "Heart failure",
                          "Cardiac arrest",
                          "Obesity-associated morbidity",
                          "Health effects of tobacco",
                          "Hypercholesterolemia",
                          "Sedentary lifestyle",
                          "Heart cancer",
                          "Metastasis",
                          "Lung cancer",
                          "Breast cancer",
                          "Cardiac muscle",
                          "Hypertrophy",
                          "Mitosis",
                          "Anatomical terms of location",
                          "Lobes of liver",
                          "Common bile duct",
                          "Lipid metabolism",
                          "Cystic duct",
                          "Common hepatic duct",
                          "Cystic artery",
                          "Hepatic artery proper",
                          "Biliary tract",
                          "Gallstone",
                          "Biliary colic",
                          "Cholecystectomy",
                          "Gallbladder cancer",
                          "List of systems of the human body",
                          "Human digestive system",
                          "Tongue",
                          "Esophagus",
                          "Gastrointestinal tract",
                          "Rectum",
                          "Pancreas",
                          "Salivary gland",
                          "Molecule",
                          "Fat",
                          "Vitamin",
                          "Mineral (nutrient)",
                          "Swallowing",
                          "Peristalsis",
                          "Human mouth",
                          "Gastric acid",
                          "Chewing",
                          "Chyme",
                          "Human feces",
                          "Human anus",
                          "Pituitary gland",
                          "Thyroid",
                          "Adrenal gland",
                          "Parathyroid gland",
                          "Gonad",
                          "Lymph node",
                          "Cytokine",
                          "Toll-like receptor",
                          "Integumentary system",
                          "Sweat gland",
                          "Nail (anatomy)",
                          "Sebaceous gland",
                          "Human musculoskeletal system",
                          "Joint",
                          "Cartilage",
                          "Calcium in biology",
                          "Muscular system",
                          "Neuron",
                          "Glia",
                          "Nerve",
                          "Ganglion",
                          "Grey matter",
                          "Human brain",
                          "Thought",
                          "Memory",
                          "Sensory processing",
                          "Special senses",
                          "Hearing",
                          "Taste",
                          "Sense of smell",
                          "Human eye",
                          "Ear",
                          "Human nose",
                          "Central nervous system",
                          "Spinal cord",
                          "Peripheral nervous system",
                          "Motion",
                          "Sense",
                          "Cognition",
                          "Consciousness",
                          "Sensory neuron",
                          "Digestion",
                          "Motor neuron",
                          "Somatic nervous system",
                          "Somatic nervous system",
                          "Autonomic nervous system",
                          "Epilepsy",
                          "Seizure",
                          "Multiple sclerosis",
                          "Myelin",
                          "Speech",
                          "ALS",
                          "Human reproductive system",
                          "Male reproductive system",
                          "Female reproductive system",
                          "Puberty",
                          "Ovulation",
                          "Menstruation",
                          "Pubic hair",
                          "Underarm hair",
                          "Breast",
                          "Uterus",
                          "Vagina",
                          "Human penis",
                          "Testicle",
                          "Fallopian tube",
                          "Oocyte",
                          "Menstrual cycle",
                          "Vulva",
                          "Labia",
                          "Vulval vestibule",
                          "Scrotum",
                          "Sperm",
                          "Ejaculation",
                          "Semen",
                          "Epididymis",
                          "Polycystic ovary syndrome",
                          "Vas deferens",
                          "Male accessory gland",
                          "Testicular torsion",
                          "Sexually transmitted infection",
                          "Syphilis",
                          "HIV",
                          "Chlamydia",
                          "Human papillomavirus infection",
                          "Genital wart",
                          "Penile cancer",
                          "Testicular cancer",
                          "Prostate cancer",
                          "Ovarian cancer",
                          "Cervical cancer",
                          "Vaginal cancer",
                          "Fallopian tube cancer",
                          "Uterine cancer",
                          "Vulvar cancer",
                          "Pharynx",
                          "Trachea",
                          "Atmosphere of Earth",
                          "Thoracic diaphragm",
                          "Vacuum",
                          "Pulmonary alveolus",
                          "Inflammation",
                          "Mucus",
                          "Asthma",
                          "Wheeze",
                          "Shortness of breath",
                          "Pneumonia",
                          "Tuberculosis",
                          "Chronic obstructive pulmonary disease",
                          "Smoking",
                          "Ureter",
                          "Bladder",
                          "Urethra",
                          "Nephron",
                          "Smooth muscle",
                          "Creatinine",
                          "Electrolyte imbalance",
                          "Pelvis",
                          "Urethral sphincters",
                          "Urination",
                          "Urologic disease",
                          "Kidney stone disease",
                          "Urinary tract infection",
                          "Kidney dialysis",
                          "Kidney transplantation",
                          "Bladder cancer",
                          "Kidney cancer",
                          "Urethral cancer",
                          "Ureteral cancer",
                          "Limb (anatomy)",
                          "Adipose tissue",
                          "Spinal column",
                          "Sesamoid bone",
                          "Accessory muscle",
                          "Superior vena cava",
                          "Inferior vena cava",
                          "Aorta",
                          "Blood–brain barrier",
                          "Abdominal cavity",
                          "Body shape",
                          "Body proportions",
                          "Large intestine"]

    subjects_to_find_4 = ["Sex",
                          "Animal sexual behaviour",
                          "Gender",
                          "Hermaphrodite",
                          "Intersex",
                          "Dioecy",
                          "Male",
                          "Female",
                          "Gender of connectors and fasteners",
                          "XY sex-determination system",
                          "Phenotypic trait",
                          "Sexual reproduction",
                          "Gamete",
                          "Zygote",
                          "Offspring",
                          "Organism",
                          "Sperm",
                          "Egg cell",
                          "Sex-determination system",
                          "Mammal",
                          "Y chromosome",
                          "X chromosome",
                          "ZW sex-determination system",
                          "XO sex-determination system",
                          "Environmental sex determination",
                          "Temperature-dependent sex determination",
                          "Sexual dimorphism",
                          "Sexing",
                          "Sexual characteristics",
                          "Sexual selection",
                          "Mate choice",
                          "Mating in fungi",
                          "Mating type",
                          "Isogamy",
                          "Anisogamy",
                          "Eukaryote",
                          "DNA",
                          "Chromosome",
                          "Homologous chromosome",
                          "Meiosis",
                          "Genetic recombination",
                          "Chromosomal crossover",
                          "Fertilisation",
                          "Animal",
                          "Plant",
                          "Spore",
                          "Mitosis",
                          "Multicellular organism",
                          "Oogamy",
                          "Motility",
                          "Egg cell",
                          "Autogamy",
                          "Embryo",
                          "Flagellum",
                          "Ovary",
                          "Egg",
                          "Mating",
                          "External fertilization",
                          "Internal fertilization",
                          "Cloaca",
                          "Sex organ",
                          "Intromittent organ",
                          "Penis",
                          "Insemination",
                          "Sexual intercourse",
                          "Uterus",
                          "Gestation",
                          "Traumatic insemination",
                          "Embryophyte",
                          "Seed plant",
                          "Gametophyte",
                          "Gametophyte",
                          "Pollen",
                          "Stamen",
                          "Stigma (botany)",
                          "Ovule",
                          "Seed",
                          "Flower",
                          "Flowering plant",
                          "Style (botany)",
                          "Ovary (botany)",
                          "Pollen tube",
                          "Self-incompatibility",
                          "Sequential hermaphroditism",
                          "Heterostyly",
                          "Pine",
                          "Conifer",
                          "Hummingbird",
                          "Bat",
                          "Pollination",
                          "Fungus",
                          "Baker's yeast",
                          "Dikarya",
                          "Mushroom",
                          "Sexual system",
                          "Gonochorism",
                          "Insect",
                          "Monoecy",
                          "Gymnosperm",
                          "Evolution of sexual reproduction",
                          "Conifer",
                          "Convergent evolution",
                          "Green algae",
                          "Outcrossing",
                          "Vertebrate land invasion",
                          "Bangiomorpha",
                          "DNA damage (naturally occurring)",
                          "Complementation (genetics)",
                          "Mutation",
                          "Genetic variation",
                          "Haplodiploidy",
                          "Sex chromosome",
                          "Marchantia polymorpha",
                          "Silene",
                          "Crocodile",
                          "Sexual differentiation",
                          "Phenotype",
                          "Klinefelter syndrome",
                          "XYY syndrome",
                          "Turner syndrome",
                          "Trisomy X",
                          "Platypus",
                          "Monotreme",
                          "Drosophila melanogaster",
                          "Crustacean",
                          "Lepidoptera",
                          "Arachnid",
                          "Silverfish",
                          "Apterygota",
                          "Dragonfly",
                          "Palaeoptera",
                          "Grasshopper",
                          "Exopterygota",
                          "Gryllus",
                          "Caenorhabditis elegans",
                          "ZO sex-determination system",
                          "Fern",
                          "Ceratopteris",
                          "Antheridiogen",
                          "Pheromone",
                          "Bonelliidae",
                          "Teleost",
                          "Clownfish",
                          "Lineage (evolution)",
                          "Wrasse",
                          "Arisaema triphyllum",
                          "Reptile",
                          "Turtle",
                          "Alligator snapping turtle",
                          "Honey bee",
                          "Ant",
                          "Sex ratio",
                          "Arrhenotoky",
                          "Pseudo-arrhenotoky",
                          "Ratio",
                          "Population",
                          "Fisher's principle",
                          "Parthenogenesis",
                          "Androgenesis",
                          "Eusociality",
                          "Wasp",
                          "Bee",
                          "Termite",
                          "Sex differences in medicine",
                          "Sex differences in intelligence",
                          "Neuroscience of sex differences",
                          "Sex differences in human physiology",
                          "Richard Dawkins",
                          "Sexual dimorphism",
                          "Secondary sex characteristic",
                          "Stalk-eyed fly",
                          "Sex differences in humans",
                          "Latrodectus mactans",
                          "Elephant seal",
                          "Polygyny in animals",
                          "Intraspecific competition",
                          "Anglerfish",
                          "Parasitism",
                          "Dicranum",
                          "Sphaerocarpos",
                          "Animal coloration",
                          "Handicap principle",
                          "Fitness (biology)",
                          "Coucal",
                          "Parental care",
                          "Human sexuality",
                          "Human Sexuality (book)",
                          "Masturbation",
                          "Non-penetrative sex",
                          "Oral sex",
                          "Orgy",
                          "Sexual arousal",
                          "Sex life",
                          "Courtship",
                          "Display (zoology)",
                          "Foreplay",
                          "BDSM",
                          "Emotional intimacy",
                          "Physical intimacy",
                          "Human bonding",
                          "Physiology",
                          "Human reproductive system",
                          "Libido",
                          "Marriage",
                          "Premarital sex",
                          "Extramarital sex",
                          "Taboo",
                          "Sex and the law",
                          "Social norm",
                          "Jurisdiction",
                          "Sexual assault",
                          "Age of consent",
                          "Autoeroticism",
                          "Sexual fantasy",
                          "Anal sex",
                          "Sexual penetration",
                          "Group sex",
                          "Dildo",
                          "Vibrator (sex toy)",
                          "Butt plug",
                          "Sex toy",
                          "Sexual orientation",
                          "Intimate relationship",
                          "Sexual partner",
                          "Anonymous sex",
                          "Conventional sex",
                          "Kink (sexuality)",
                          "Sexual fetishism",
                          "Fixation (psychology)",
                          "Mental disorder",
                          "Psychosocial distress",
                          "Partialism",
                          "Obesity",
                          "Body modification",
                          "Smoking",
                          "Paraphilia",
                          "Urolagnia",
                          "Necrophilia",
                          "Coprophilia",
                          "Clothing fetish",
                          "Rubber and PVC fetishism",
                          "Shoe fetishism",
                          "Leather subculture",
                          "Foot fetishism",
                          "Body fluid",
                          "Erotic lactation",
                          "List of paraphilias",
                          "Other specified paraphilic disorder",
                          "Martin Kafka",
                          "Hair fetishism",
                          "Muscle worship",
                          "Navel fetishism",
                          "Underwear fetishism",
                          "Underwear",
                          "Panties",
                          "Stocking",
                          "Pantyhose",
                          "Pacifier",
                          "Diaper fetishism",
                          "Erotic asphyxiation",
                          "Attraction to disability",
                          "Personality",
                          "Extraversion and introversion",
                          "Hypersexuality",
                          "Odds ratio",
                          "Classical conditioning",
                          "John Bancroft (sexologist)",
                          "Social cognition",
                          "Social learning theory",
                          "Operant conditioning",
                          "V. S. Ramachandran",
                          "Temporal lobe",
                          "Anterior temporal lobectomy",
                          "Roy Baumeister",
                          "Sexual fluidity",
                          "Transvestic fetishism",
                          "Cross-dressing",
                          "International Classification of Diseases",
                          "Other specified paraphilic disorder",
                          "World Health Organization",
                          "Case study",
                          "Cognitive behavioral therapy",
                          "Aversion therapy",
                          "Covert conditioning",
                          "Psychodynamics",
                          "Antiandrogen",
                          "Cyproterone acetate",
                          "Osteoporosis",
                          "Medroxyprogesterone acetate",
                          "Deep vein thrombosis",
                          "Leuprorelin",
                          "Goserelin",
                          "Selective serotonin reuptake inhibitor",
                          "Couples therapy",
                          "Sensate focus",
                          "Covert conditioning",
                          "Prevalence",
                          "French language",
                          "Portuguese language",
                          "Latin",
                          "Boot fetishism",
                          "Lingerie",
                          "Breast fetishism",
                          "Self-bondage",
                          "Bondage (BDSM)",
                          "Rape",
                          "Adultery laws",
                          "Sexual ethics",
                          "Evolutionary psychology",
                          "Human mating strategies",
                          "Behavioral ecology",
                          "Human reproduction",
                          "Life history theory",
                          "Casual dating",
                          "Friendship",
                          "Interpersonal relationship",
                          "Human sexual response cycle",
                          "Sexual stimulation",
                          "Vaginal lubrication",
                          "Clitoris",
                          "Orgasm",
                          "Fake orgasm",
                          "Refractory period (sex)",
                          "Sexual dysfunction",
                          "Sexology",
                          "Oxytocin",
                          "Hatesex",
                          "Pity Sex",
                          "Eroticism",
                          "Sexual desire",
                          "Sexual attraction",
                          "Casual sex",
                          "Pity",
                          "Human fertilization",
                          "Sexual tension",
                          "Self-determination theory",
                          "Sexually active life expectancy",
                          "Menopause",
                          "Kinsey Institute",
                          "Sex recession",
                          "Adolescent sexuality",
                          "Sexualization",
                          "Virginity",
                          "Unintended pregnancy",
                          "Sexually transmitted infection",
                          "Birth control",
                          "Combined oral contraceptive pill",
                          "Condom",
                          "Diaphragm (birth control)",
                          "Spermicide",
                          "Hormonal contraception",
                          "Mucous membrane",
                          "Safe sex",
                          "HIV/AIDS",
                          "Drug injection",
                          "Hypodermic needle",
                          "Breastfeeding",
                          "Sexuality in older age",
                          "Heterosexuality",
                          "Social policy",
                          "Sodomy law",
                          "Sexual abuse",
                          "Monogamy",
                          "Polyamory",
                          "Abstinence",
                          "Homosexuality",
                          "Sexual practices between men",
                          "Sexual practices between women",
                          "Closeted",
                          "Coming out",
                          "Outing",
                          "Down-low (sexual slang)",
                          "Men who have sex with men",
                          "Women who have sex with women",
                          "Situational sexual behavior",
                          "Sexual identity",
                          "Tribadism",
                          "Bisexuality",
                          "Pansexuality",
                          "Frot",
                          "Gender identity",
                          "Aesthetics",
                          "Romance",
                          "Gender-blind",
                          "Oxford English Dictionary",
                          "Inbreeding",
                          "Sexual inhibition",
                          "Alex Comfort",
                          "Religion and sexuality",
                          "Fidelity",
                          "Incest",
                          "Chat room",
                          "Swinging (sexual practice)",
                          "Committed relationship",
                          "Sexual revolution",
                          "Sex industry",
                          "Phone sex",
                          "Strip club",
                          "Gender role",
                          "Family honor",
                          "Chastity",
                          "Honor killing",
                          "Female genital mutilation",
                          "Gender equality",
                          "Sexual and reproductive health",
                          "Sexual and reproductive health",
                          "International Conference on Population and Development",
                          "Sexual roleplay",
                          "Dominance and submission",
                          "Sadomasochism",
                          "Self-concept",
                          "Animal roleplay",
                          "Rubber and PVC fetishism",
                          "Informed consent",
                          "Top, bottom, switch",
                          "Psychopathology",
                          "LGBTQ rights by country or territory",
                          "Same-sex relationship",
                          "Fornication",
                          "Child sexual abuse",
                          "Position of trust",
                          "Legality of incest",
                          "Frotteurism",
                          "Obscene phone call",
                          "Exhibitionism",
                          "Voyeurism",
                          "Indecent exposure",
                          "Prostitution",
                          "Client (prostitution)",
                          "Prostitution law",
                          "Prostitution by region",
                          "Forced prostitution",
                          "Procuring (prostitution)",
                          "Survival sex",
                          "Homelessness",
                          "Basic needs",
                          "Recreational drug use",
                          "Humanitarian aid",
                          "Transgender sexuality",
                          "Sociosexuality",
                          "Orgastic potency",
                          "Orgasm control",
                          "Mechanics of human sexuality",
                          "Human male sexuality",
                          "Human female sexuality",
                          "History of human sexuality",
                          "Erotic plasticity",
                          "Child sexuality",
                          "Culture",
                          "Politics",
                          "Spirituality",
                          "Religion",
                          "Ethics",
                          "Morality",
                          "Theology",
                          "Body image",
                          "Self-esteem",
                          "Value (ethics)",
                          "Attitude (psychology)",
                          "Lesbian",
                          "Stimulus (physiology)",
                          "Sex position",
                          "Muscle contraction",
                          "Mayo Clinic",
                          "Clitoral hood",
                          "Labia minora",
                          "G-spot",
                          "Glans penis",
                          "Homology (biology)",
                          "Functional magnetic resonance imaging",
                          "Anecdotal evidence",
                          "Cortical homunculus",
                          "Physical attractiveness",
                          "Facial symmetry",
                          "Modesty",
                          "Psychoanalysis",
                          "Madonna–whore complex",
                          "Sigmund Freud",
                          "Carl Jung",
                          "Immigration",
                          "Chastity belt",
                          "European colonization of the Americas",
                          "Indigenous peoples of the Americas",
                          "Puritans",
                          "Jezebel",
                          "Fingering (sexual act)",
                          "Mammy stereotype",
                          "Masters and Johnson",
                          "Ernst Gräfenberg",
                          "Beverly Whipple",
                          "Feminist views on sexuality",
                          "Feminist pornography",
                          "Feminist movement",
                          "Nancy Friday",
                          "My Secret Garden",
                          "Germaine Greer",
                          "Simone de Beauvoir",
                          "Camille Paglia",
                          "Luce Irigaray",
                          "Julia Kristeva",
                          "Political lesbianism",
                          "Second-wave feminism",
                          "Radical feminism",
                          "Sheila Jeffreys",
                          "Julie Bindel",
                          "Feminist sex wars",
                          "Opposition to pornography",
                          "Sex-positive feminism",
                          "Marital rape",
                          "Pornography",
                          "Adultery",
                          "Medical research",
                          "Social constructionism",
                          "Masculinity",
                          "Dominatrix",
                          "Clitoral vibrator",
                          "Erotica: A Journey Into Female Sexuality",
                          "Extended female sexuality",
                          "Female ejaculation",
                          "Female promiscuity",
                          "Female sexual arousal disorder",
                          "Female sodomy",
                          "Female submission",
                          "Feminist theory",
                          "Love egg",
                          "Madonna and sexuality",
                          "Medieval female sexuality",
                          "Penis envy",
                          "Porn for women",
                          "Rabbit vibrator",
                          "Sex toy party",
                          "Sexual and reproductive health and rights",
                          "Victimization of bisexual women",
                          "Women's sexuality in Francoist Spain",
                          "Women's erotica",
                          "Human sexual activity"]

    destination_folder = "../../../Datasets/WikipediaData/"
    subjects_to_find = subjects_to_find_4



    collect_and_save_articles_wikipedia(subjects_to_find, destination_folder)

    end_time = datetime.now()
    elapsed_time = calculate_elapsed_time(begin_time, end_time)
    print("__main__() - Elapsed Time =", elapsed_time)

    print("__main__() - END")
