import wikipedia
import os
from datetime import datetime



def calculate_elapsed_time(begin_time_, end_time_):
    elapsed_time_ = end_time_ - begin_time_
    days = elapsed_time_.days
    seconds = elapsed_time_.seconds
    milliseconds = elapsed_time_.microseconds // 1000
    hours, remainder = divmod(seconds, 3600)
    minutes, seconds = divmod(remainder, 60)
    years, days = divmod(days, 365)
    months, days = divmod(days, 30)
    formatted_elapsed_time_ = f"{years:04}:{months:02}:{days:02}:{hours:02}:{minutes:02}:{seconds:02}:{milliseconds:03}"
    return formatted_elapsed_time_


def collect_and_save_articles_wikipedia(subjects_to_find_, destination_folder_="dati_wikipedia"):
    """
    Search and download Wikipedia articles by topic,
    saving them in separate text files.

    Args:
        subjects_to_find_ (list): List of strings containing the names of the arguments to search for.
        destination_folder_ (str): The name of the folder where to save the files.
    """
    print("collect_and_save_articles_wikipedia() - BEGIN")
    # 1. Configurazione Iniziale
    print(f"Tentativo di creare la cartella: {destination_folder_}")
    os.makedirs(destination_folder_, exist_ok=True)
    wikipedia.set_lang("en")  # Imposta la lingua di Wikipedia (italiano)

    downloaded_articles_ = 0

    for subject_ in subjects_to_find_:
        print(f"\n--- Elaborazione di: '{subject_}' ---")

        try:
            # 2. Ottenere la Pagina (Potrebbe sollevare un'eccezione se non trovata)
            page_ = wikipedia.page(subject_, auto_suggest=False)

            # 3. Pulizia del Nome del File
            # Rimuove caratteri non validi per i nomi di file
            file_name_ = "".join(c for c in subject_ if c.isalnum() or c in (' ', '_')).rstrip().replace(' ', '_')
            file_path_ = os.path.join(destination_folder_, f"{file_name_}.txt")

            # 4. Salvare il Contenuto nel File
            with open(file_path_, 'w', encoding='utf-8') as f:
                # La proprietà 'content' restituisce l'intero testo della page_
                f.write(page_.content)

            print(f"✔ Articolo salvato in: {file_path_}")
            downloaded_articles_ += 1

        except wikipedia.exceptions.PageError:
            print(f"❌ Errore: Pagina di Wikipedia non trovata per l'subject_ '{subject_}'. Saltato.")
        except wikipedia.exceptions.DisambiguationError as e:
            print(f"⚠️ Attenzione: L'subject_ '{subject_}' è ambiguo. Opzioni: {e.options[:5]}. Saltato.")
        except Exception as e:
            print(f"collect_and_save_articles_wikipedia() - Generic error while processing '{subject_}': {e}. Saltato.")

    print(f"\n--- Finito. {downloaded_articles_} articoli salvati. ---")
    print("collect_and_save_articles_wikipedia() - END")



if __name__ == "__main__":
    print("__main__() - BEGIN")

    begin_time = datetime.now()

    subjects_to_find_1 = [
        "Liver",
        "Liver cirrhosis",
        "Bile",
        "Liver disease",
        "Human anatomy",
        "Hepatotoxicity",
        "Liver failure",
        "Liver support system",
        "Elevated transaminases",
        "Metabolic dysfunction–associated steatotic liver disease",
        "Liver regeneration",
        "Fatty liver disease",
        "Acute liver failure",
        "Hepatomegaly",
        "Lobules of liver",
        "Chronic liver disease",
        "Alanine transaminase",
        "AST/ALT ratio",
        "Liver transplantation",
        "Hepatorenal syndrome",
        "Hepatocellular carcinoma",
        "Liver metastasis",
        "Jaundice",
        "Bilirubin",
        "Pre-eclampsia",
        "Alkaline phosphatase",
        "Kupffer cell",
        "Paracetamol",
        "Shark liver oil",
        "HepaRG",
        "Liver cancer",
        "Alpha-1 antitrypsin deficiency",
        "Schistosomiasis",
        "Gallbladder",
        "Paracetamol poisoning",
        "Aspartate transaminase",
        "Lorazepam",
        "Cholangiocarcinoma",
        "Organ (biology)",
        "Urea-to-creatinine ratio",
        "Sarcoidosis",
        "Foie gras",
        "Alcoholic hepatitis",
        "Interventional radiology",
        "Polycystic liver disease",
        "Sulfamethoxazole",
        "Hypoalbuminemia",
        "Human serum albumin",
        "Blood test",
        "Anorexia nervosa",
        "Hepatitis",
        "Adult-onset Still's disease",
        "Intrahepatic cholestasis of pregnancy",
        "Alcoholic liver disease",
        "TNT",
        "Reye syndrome",
        "Primary sclerosing cholangitis",
        "Cholestasis",
        "Autoimmune hepatitis",
        "Liver cytology",
        "Bone tumor",
        "Basic metabolic panel",
        "Lipotropic",
        "Hepatic encephalopathy",
        "Liver biopsy",
        "Elevated alkaline phosphatase",
        "Hyperbilirubinemia in adults",
        "Hepatitis C",
        "Primary biliary cholangitis",
        "Sanford Rosenthal",
        "Wilson's disease",
        "Bromsulfthalein",
        "Ezetimibe",
        "Congestive hepatopathy",
        "Agaricus subrufescens",
        "Organ-on-a-chip",
        "Valproate",
        "Rodenticide",
        "Small intestine"
    ]


    subjects_to_find_2 = ["Blood",
                          "Hemoglobin",
                          "Glucose",
                          "Amino acid",
                          "Hormone",
                          "Blood plasma",
                          "Red blood cell",
                          "Ion",
                          "White blood cell",
                          "Cell (biology)",
                          "Protein",
                          "Gnathostomata",
                          "Platelet",
                          "Adaptive immune system",
                          "Coagulation",
                          "Blood vessel",
                          "Heart",
                          "Body fluid",
                          "Water",
                          "Human",
                          "Vertebrate",
                          "Lung",
                          "Circulatory system",
                          "Metabolic waste",
                          "Nutrient",
                          "Artery",
                          "Vein",
                          "Metabolism",
                          "Anatomy",
                          "Histology",
                          "Connective tissue",
                          "Fibrinogen",
                          "Oxygen",
                          "Fatty acid",
                          "Plasma protein",
                          "Blood lipids",
                          "Carbon dioxide",
                          "Urea",
                          "Lactic acid",
                          "Antibody",
                          "Tissue (biology)",
                          "Thermoregulation",
                          "Blood volume",
                          "Non-Newtonian fluid",
                          "Hemorheology",
                          "Cell nucleus",
                          "Endothelium",
                          "Organelle",
                          "Glycoprotein",
                          "Hematocrit",
                          "Immune system",
                          "Human blood group systems",
                          "Pathogen",
                          "Leukemia",
                          "Platelet plug",
                          "List of human blood components",
                          "Serum albumin",
                          "Lipoprotein",
                          "Electrolyte",
                          "Sodium in biology",
                          "Chloride",
                          "pH",
                          "Acid–base homeostasis",
                          "Base (chemistry)",
                          "Acid",
                          "pCO2",
                          "Bicarbonate",
                          "Homeostasis",
                          "Respiratory system",
                          "Urinary system",
                          "Arterial blood gas test",
                          "Reference ranges for blood tests",
                          "Protein structure",
                          "Pulmonary artery",
                          "Ventricle (heart)",
                          "Pulmonary vein",
                          "Venous blood",
                          "Skeletal muscle",
                          "Bone marrow",
                          "Haematopoiesis",
                          "Myelopoiesis",
                          "Thymus",
                          "Mediastinum",
                          "T cell",
                          "Endocrine gland",
                          "Hypothalamus",
                          "Kidney",
                          "Spleen",
                          "Urine",
                          "Mammal",
                          "Umbilical artery",
                          "Arteriole",
                          "Capillary",
                          "Venule",
                          "Oxygen saturation (medicine)",
                          "Fetus",
                          "Placenta",
                          "Fetal hemoglobin",
                          "Carbonic anhydrase",
                          "Carbamino",
                          "Allosteric regulation",
                          "Haldane effect",
                          "Bohr effect",
                          "Lymphatic system",
                          "Lymph",
                          "Thoracic duct",
                          "Subclavian vein",
                          "Erection",
                          "Erectile tissue",
                          "Penis",
                          "Clitoris",
                          "Blood donation",
                          "Carbon monoxide poisoning",
                          "Carbon monoxide",
                          "Carboxyhemoglobin",
                          "Cyanide",
                          "Methemoglobin",
                          "Sulfhemoglobinemia",
                          "Visual cortex",
                          "Biliverdin",
                          "Shock (circulatory)",
                          "Internal bleeding",
                          "Dehydration",
                          "Orthostatic hypotension",
                          "Syncope (medicine)",
                          "Cardiac output",
                          "Atherosclerosis",
                          "Perfusion",
                          "Hyperlipidemia",
                          "Hypertension",
                          "Diabetes",
                          "Thrombosis",
                          "Necrosis",
                          "Hematology",
                          "Anemia",
                          "Thalassemia",
                          "Malnutrition",
                          "Blood transfusion",
                          "Genetic disorder",
                          "Blood bank",
                          "Blood type",
                          "Sickle cell disease",
                          "Cancer",
                          "Polycythemia vera",
                          "Essential thrombocythemia",
                          "Precancerous condition",
                          "Myelodysplastic syndrome",
                          "Haemophilia",
                          "Hemarthrosis",
                          "Coagulopathy",
                          "Thrombophilia",
                          "Hepatitis B",
                          "Blood-borne disease",
                          "Biological hazard",
                          "Bloodstream infection",
                          "Sepsis",
                          "Malaria",
                          "Trypanosomiasis",
                          "ABO blood group system",
                          "Rh blood group system",
                          "Cross-matching",
                          "Intravenous therapy",
                          "Antibiotic",
                          "Chemotherapy",
                          "Bloodletting",
                          "Evidence-based medicine",
                          "Iron overload",
                          "Blood type",
                          "Polycythemia",
                          "Hippocrates",
                          "Erythrocyte sedimentation rate",
                          "Heredity",
                          "Autotransfusion",
                          "Blood pressure",
                          "Blood phobia",
                          "Blood substitute",
                          "Hemodynamics",
                          "Luminol",
                          "Oct-1-en-3-one",
                          "Blood residue",
                          "Pressure",
                          "Brachial artery",
                          "Cardiac cycle",
                          "Millimetre of mercury",
                          "Respiratory rate",
                          "Heart rate",
                          "Auscultation",
                          "Stethoscope",
                          "Mercury (element)",
                          "Sphygmomanometer",
                          "Ambulatory blood pressure",
                          "Arterial stiffness",
                          "Nervous system",
                          "Endocrine system",
                          "Baroreceptor",
                          "Hypotension",
                          "Stroke",
                          "Cardiovascular disease",
                          "Kidney failure",
                          "Stress (biology)",
                          "Sex",
                          "Peripheral artery disease",
                          "Aortic dissection",
                          "Pregnancy",
                          "Systolic hypertension",
                          "Intensive care medicine",
                          "Pulmonary circulation",
                          "Catheter",
                          "Jugular venous pressure",
                          "Respiratory disease",
                          "Central venous pressure",
                          "Portal venous pressure",
                          "Pulmonary edema",
                          "Pulmonary hypertension",
                          "Aortic pressure",
                          "Hypertension",
                          "Hypertensive emergency",
                          "Atrium (heart)"]

    subjects_to_find_3 = ["Skeleton",
                          "Human skeleton",
                          "Gray's Anatomy",
                          "Organ system",
                          "Human head",
                          "Hair",
                          "Neck",
                          "Torso",
                          "Thorax",
                          "Abdomen",
                          "Sex organ",
                          "Arm",
                          "Hand",
                          "Human leg",
                          "Foot",
                          "Human tooth",
                          "Bone",
                          "Muscle",
                          "Tendon",
                          "Ligament",
                          "Lymphatic vessel",
                          "Physiology",
                          "Embryology",
                          "Anatomical variation",
                          "Sugar",
                          "Iron",
                          "Health professional",
                          "Composition of the human body",
                          "Hydrogen",
                          "Carbon",
                          "Calcium",
                          "Phosphorus",
                          "Extracellular fluid",
                          "Body water",
                          "pH",
                          "Sodium",
                          "Potassium",
                          "Phosphate",
                          "List of human cell types",
                          "Extracellular matrix",
                          "Collagen",
                          "DNA damage (naturally occurring)",
                          "Human genome",
                          "DNA repair",
                          "DNA",
                          "Mutation",
                          "Genome",
                          "Genetics",
                          "Transcription (biology)",
                          "RNA",
                          "Microscope",
                          "Epithelium",
                          "Nervous tissue",
                          "Stomach",
                          "Human skin",
                          "Body cavity",
                          "Abdominopelvic cavity",
                          "Pleural cavity",
                          "Thoracic cavity",
                          "Pericardium",
                          "Infection",
                          "Pericardial fluid",
                          "Systole",
                          "Cardiac conduction system",
                          "Atrioventricular node",
                          "Sinoatrial node",
                          "Coronary arteries",
                          "Coronary artery disease",
                          "List of causes of death by rate",
                          "Ischemia",
                          "Cardiac muscle",
                          "Myocardial infarction",
                          "Heart failure",
                          "Cardiac arrest",
                          "Obesity-associated morbidity",
                          "Health effects of tobacco",
                          "Hypercholesterolemia",
                          "Sedentary lifestyle",
                          "Heart cancer",
                          "Metastasis",
                          "Lung cancer",
                          "Breast cancer",
                          "Cardiac muscle",
                          "Hypertrophy",
                          "Mitosis",
                          "Anatomical terms of location",
                          "Lobes of liver",
                          "Common bile duct",
                          "Lipid metabolism",
                          "Cystic duct",
                          "Common hepatic duct",
                          "Cystic artery",
                          "Hepatic artery proper",
                          "Biliary tract",
                          "Gallstone",
                          "Biliary colic",
                          "Cholecystectomy",
                          "Gallbladder cancer",
                          "List of systems of the human body",
                          "Human digestive system",
                          "Tongue",
                          "Esophagus",
                          "Gastrointestinal tract",
                          "Rectum",
                          "Pancreas",
                          "Salivary gland",
                          "Molecule",
                          "Fat",
                          "Vitamin",
                          "Mineral (nutrient)",
                          "Swallowing",
                          "Peristalsis",
                          "Human mouth",
                          "Gastric acid",
                          "Chewing",
                          "Chyme",
                          "Human feces",
                          "Human anus",
                          "Pituitary gland",
                          "Thyroid",
                          "Adrenal gland",
                          "Parathyroid gland",
                          "Gonad",
                          "Lymph node",
                          "Cytokine",
                          "Toll-like receptor",
                          "Integumentary system",
                          "Sweat gland",
                          "Nail (anatomy)",
                          "Sebaceous gland",
                          "Human musculoskeletal system",
                          "Joint",
                          "Cartilage",
                          "Calcium in biology",
                          "Muscular system",
                          "Neuron",
                          "Glia",
                          "Nerve",
                          "Ganglion",
                          "Grey matter",
                          "Human brain",
                          "Thought",
                          "Memory",
                          "Sensory processing",
                          "Special senses",
                          "Hearing",
                          "Taste",
                          "Sense of smell",
                          "Human eye",
                          "Ear",
                          "Human nose",
                          "Central nervous system",
                          "Spinal cord",
                          "Peripheral nervous system",
                          "Motion",
                          "Sense",
                          "Cognition",
                          "Consciousness",
                          "Sensory neuron",
                          "Digestion",
                          "Motor neuron",
                          "Somatic nervous system",
                          "Somatic nervous system",
                          "Autonomic nervous system",
                          "Epilepsy",
                          "Seizure",
                          "Multiple sclerosis",
                          "Myelin",
                          "Speech",
                          "ALS",
                          "Human reproductive system",
                          "Male reproductive system",
                          "Female reproductive system",
                          "Puberty",
                          "Ovulation",
                          "Menstruation",
                          "Pubic hair",
                          "Underarm hair",
                          "Breast",
                          "Uterus",
                          "Vagina",
                          "Human penis",
                          "Testicle",
                          "Fallopian tube",
                          "Oocyte",
                          "Menstrual cycle",
                          "Vulva",
                          "Labia",
                          "Vulval vestibule",
                          "Scrotum",
                          "Sperm",
                          "Ejaculation",
                          "Semen",
                          "Epididymis",
                          "Polycystic ovary syndrome",
                          "Vas deferens",
                          "Male accessory gland",
                          "Testicular torsion",
                          "Sexually transmitted infection",
                          "Syphilis",
                          "HIV",
                          "Chlamydia",
                          "Human papillomavirus infection",
                          "Genital wart",
                          "Penile cancer",
                          "Testicular cancer",
                          "Prostate cancer",
                          "Ovarian cancer",
                          "Cervical cancer",
                          "Vaginal cancer",
                          "Fallopian tube cancer",
                          "Uterine cancer",
                          "Vulvar cancer",
                          "Pharynx",
                          "Trachea",
                          "Atmosphere of Earth",
                          "Thoracic diaphragm",
                          "Vacuum",
                          "Pulmonary alveolus",
                          "Inflammation",
                          "Mucus",
                          "Asthma",
                          "Wheeze",
                          "Shortness of breath",
                          "Pneumonia",
                          "Tuberculosis",
                          "Chronic obstructive pulmonary disease",
                          "Smoking",
                          "Ureter",
                          "Bladder",
                          "Urethra",
                          "Nephron",
                          "Smooth muscle",
                          "Creatinine",
                          "Electrolyte imbalance",
                          "Pelvis",
                          "Urethral sphincters",
                          "Urination",
                          "Urologic disease",
                          "Kidney stone disease",
                          "Urinary tract infection",
                          "Kidney dialysis",
                          "Kidney transplantation",
                          "Bladder cancer",
                          "Kidney cancer",
                          "Urethral cancer",
                          "Ureteral cancer",
                          "Limb (anatomy)",
                          "Adipose tissue",
                          "Spinal column",
                          "Sesamoid bone",
                          "Accessory muscle",
                          "Superior vena cava",
                          "Inferior vena cava",
                          "Aorta",
                          "Blood–brain barrier",
                          "Abdominal cavity",
                          "Body shape",
                          "Body proportions",
                          "Large intestine"]

    destination_folder = "../../../Datasets/WikipediaData/"
    subjects_to_find = subjects_to_find_3



    collect_and_save_articles_wikipedia(subjects_to_find, destination_folder)

    end_time = datetime.now()
    elapsed_time = calculate_elapsed_time(begin_time, end_time)
    print("__main__() - Elapsed Time =", elapsed_time)

    print("__main__() - END")
